#Max number of times you can use /back
#Range: > 0
maxBack = 5
#Max homes
#Range: > 0
maxHomes = 5
#/back cooldown in seconds
#Range: 0 ~ 604800
backCooldown = 30
#/spawn cooldown in seconds
#Range: 0 ~ 604800
spawnCooldown = 30
#/warp cooldown in seconds
#Range: 0 ~ 604800
warpCooldown = 30
#/home cooldown in seconds
#Range: 0 ~ 604800
homeCooldown = 20
#/tpa cooldown in seconds
#Range: 0 ~ 604800
tpaCooldown = 30
#/rtp cooldown in seconds
#Range: 0 ~ 604800
rtpCooldown = 600
#Number of tries before /rtp gives up
#Range: 1 ~ 1000
rtpMaxTries = 10
#/rtp min distance from spawn point
#Range: 0.0 ~ 3.0E7
rtpMinDistance = 1000.0
#/rtp max distance from spawn point
#Range: 0.0 ~ 3.0E7
rtpMaxDistance = 10000.0

