
[extra]
	#You can disable disable the lockon feature here.
	ENABLE_LOCKON = true

[gear]
	#Crucible Sword/Maruader Axe Max Damage
	CRUCIBLE_MARUADER_MAXDAMAGE = 5

[spawn_weight]
	#Spawn weight of Common Demons.
	COMMON_DEMON_SPAWN_WEIGHT = 30
	#Spawn weight of Heavy Demons.
	HEAVY_DEMON_SPAWN_WEIGHT = 10

