
["Hostile Water Mobs"]
	#riverGuardianSpawnCap
	#Range: 0 ~ 100
	riverGuardianSpawnCap = 15
	#riverGuardianSpawnChance
	#Range: 0 ~ 100
	riverGuardianSpawnChance = 6
	#Debug Level: 0 = Off, 1 = Log, 2 = Chat+Log
	#Range: 0 ~ 2
	debugLevel = 0

