
#WorldGen settings
[worldGen]

	#Aluminium
	[worldGen.aluminium]
		#Defines the amount of veins per chunk
		#Range: > 0
		amount = 0
		#Defines the maximum amount of blocks in a vein
		#Range: > 0
		size = 0
		#Defines the maximum height at which a vein can be generated
		#Range: 0 ~ 256
		maxHeight = 64

	#Quartz Crystal Cluster
	[worldGen.quartzCrystalCluster]
		#Defines the max amount of crystal clusters per chunk
		#Range: > 0
		amount = 2
		#Defines the amount of attempts to generate crystal clusters per chunk
		#Range: > 0
		generationAttempts = 32

	#Zychorite
	[worldGen.zychorite]
		#Defines the amount of veins per chunk
		#Range: > 0
		amount = 4
		#Defines the maximum amount of blocks in a vein
		#Range: > 0
		size = 9
		#Defines the maximum height at which a vein can be generated
		#Range: 0 ~ 256
		maxHeight = 32
		#Defines the percentage of the vein that will be filled with Zychorium Ore's
		#Range: 0 ~ 100
		orePercentage = 50

