events.listen('recipes', (event) => {
    event.replaceInput({}, 'minecraft:stone', '#forge:stone', true);
    event.replaceInput({}, 'thermal:apatite', '#forge:gems/apatite');
    event.replaceInput({ type: 'minecraft:crafting_shapeless' }, 'minecraft:stone', '#forge:stone', true);
    event.replaceInput({}, 'minecraft:diamond', '#forge:gems/diamond', true);
    event.replaceInput({}, 'minecraft:emerald', '#forge:gems/emerald', true);
    event.replaceInput({}, 'minecraft:chest', '#forge:chests/wooden', true);
    event.replaceInput({}, 'minecraft:redstone', '#forge:dusts/redstone', true);
    event.replaceInput({}, 'minecraft:paper', '#forge:paper', true);
    event.replaceInput({}, 'minecraft:stone_button', '#minecraft:buttons', true);
    event.replaceInput({}, 'minecraft:bucket', '#forge:buckets', true);
    event.replaceInput({}, 'minecraft:crafting_table', '#forge:workbench', true);
    event.replaceInput({}, 'immersiveengineering:hammer', '#forge:tools/hammer', true);
    event.replaceInput({}, 'emendatusenigmatica:enigmatic_hammer', '#forge:tools/hammer', true);
    event.replaceInput({}, 'minecraft:hopper', '#forge:tools/hopper', true);
    event.replaceInput({}, 'minecraft:piston', '#forge:piston', true);
    event.replaceInput({}, 'thermal:cinnabar', '#forge:gems/cinnabar');
    event.replaceInput({}, 'thermal:sulfur', '#forge:gems/sulfur');
    event.replaceInput({}, 'thermal:apatite', '#forge:gems/apatite');
    event.replaceInput({}, 'thermal:niter', '#forge:gems/niter');
    event.replaceInput({}, 'thermal:bitumen', '#forge:gems/bitumen', true);
    event.replaceInput({}, 'thermal:coal_coke', '#forge:gems/coal_coke');
    event.replaceInput({}, 'rftoolsbase:dimensionalshard', '#forge:gems/dimensional');
    event.replaceInput({}, 'immersivepetroleum:bitumen', '#forge:gems/bitumen', true);
    event.replaceInput({}, 'immersiveengineering:slag', '#forge:slag');
    event.replaceInput({}, 'thermal:slag', '#forge:slag');
    event.replaceInput({}, 'minecraft:iron_ore', '#forge:ores/iron');
    event.replaceInput({}, 'minecraft:gold_ore', '#forge:ores/gold');
    event.replaceInput({}, 'pneumaticcraft:wheat_flour', '#forge:dusts/flour');
    event.replaceInput({}, 'create:wheat_flour', '#forge:dusts/flour');
    event.replaceInput({ type: 'minecraft:crafting_shaped' }, 'minecraft:netherrack', '#forge:netherrack');
});