onEvent('recipes', event => {

  //Iron Furnace upgrades recipes removed
  event.remove({id: 'ironfurnaces:gold_furnace2'})
  event.remove({id: 'ironfurnaces:iron_furnace2'})
  event.remove({id: 'ironfurnaces:obsidian_furnace2'})
  event.remove({id: 'ironfurnaces:silver_furnace2'})
  event.remove({id: 'ironfurnaces:upgrade_iron'})
  event.remove({id: 'ironfurnaces:upgrade_gold'})
  event.remove({id: 'ironfurnaces:upgrade_diamond'})
  event.remove({id: 'ironfurnaces:upgrade_emerald'})
  event.remove({id: 'ironfurnaces:upgrade_obsidian'})
  event.remove({id: 'ironfurnaces:upgrade_crystal'})
  event.remove({id: 'ironfurnaces:upgrade_netherite'})
  event.remove({id: 'ironfurnaces:upgrade_copper'})
  event.remove({id: 'ironfurnaces:upgrade_silver'})
  event.remove({id: 'ironfurnaces:upgrade_obsidian2'})
  event.remove({id: 'ironfurnaces:upgrade_iron2'})
  event.remove({id: 'ironfurnaces:upgrade_silver2'})
  event.remove({id: 'ironfurnaces:upgrade_allthemodium'})
  event.remove({id: 'ironfurnaces:upgrade_vibranium'})
  event.remove({id: 'ironfurnaces:upgrade_unobtainium'})
})